# Generated by Django 5.2 on 2025-04-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userplan_plan_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='added_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
